### ISSUE TITLE
Rare GC crash

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#602]
A few weeks ago, @fieker reported a crash that seemed to be related to the GAp-Julia GC integration; it only occurred for him on a system with constrained memory availability. Stack trace:
```
#0  FindLiveRangeReverse (end=0x7fff6af55000, start=<optimized out>, arr=0xdd89230)
    at src/julia_gc.c:475
#1  SafeScanTaskStack (stack=stack@entry=0xdd89230, start=start@entry=0x7fff6ab55000,
    end=end@entry=0x7fff6af55000) at src/julia_gc.c:594
#2  0x00007fffb9d8923f in ScanTaskStack (end=<optimized out>, start=0x7fff6ab55000,
    task=0x7fff8f285ae0, rescan=1) at src/julia_gc.c:619
#3  GapTaskScanner (task=0x7fff8f285ae0, root_task=<optimized out>) at src/julia_gc.c:795
#4  0x00007ffff78ff768 in gc_mark_loop (ptls=ptls@entry=0x7ffff36dd4d8, sp=...)
    at /buildworker/worker/package_linux64/build/src/gc.c:2512
#5  0x00007ffff7901420 in _jl_gc_collect (ptls=ptls@entry=0x7ffff36dd4d8,
    collection=collection@entry=JL_GC_AUTO)
    at /buildworker/worker/package_linux64/build/src/gc.c:2902
#6  0x00007ffff7902ca1 in jl_gc_collect (collection=collection@entry=JL_GC_AUTO)
    at /buildworker/worker/package_linux64/build/src/gc.c:3108
#7  0x00007ffff7902fbb in maybe_collect (ptls=0x7ffff36dd4d8)
    at /buildworker/worker/package_linux64/build/src/gc.c:827
#8  jl_gc_pool_alloc (ptls=0x7ffff36dd4d8, pool_offset=<optimized out>, osize=80)
    at /buildworker/worker/package_linux64/build/src/gc.c:1142
#9  0x00007ffff79036e3 in jl_gc_alloc_ (
    ty=ty@entry=0x7fffde04bf70 <jl_system_image_data+3939504>, sz=sz@entry=64,
    ptls=<optimized out>)
    at /buildworker/worker/package_linux64/build/src/julia_internal.h:277
#10 jl_gc_alloc (ptls=<optimized out>, sz=sz@entry=64,

```

@rbehrends investigated and was eventually able to reliably reproduce the issue... until it went away after some Oscar components updated.

Right now it is unclear how this can happen. One possible issue is that this is caused by the fact that GAP_jll was compiled against Julia 1.4 but is used in Julia 1.5. While we tried to make it a "universal binary" by manually adjusting for all ABI changes, it is entirely possible that we missed something here.

Unfortunately @rbehrends currently cannot reproduce the issue anymore, I think... (and we don't employ him anymore)

**Comment by fingolfin** [comment]
I suspect this was an out o memory crash. In any case, we haven't seen it again since then. I also cannot reproduce it right now. So closing (for now, at least)
